### ISSUE TITLE
Need more customization

### ISSUE THREAD

**Issue by Monabr** [SuddenH4X/awesome-app-rating#17]
Hello. I want to immedeatly go to google play if rates, for example, more than 3, skiping "rate now" dialog, add this opportunity please. On the other hand if i check the rates customly i can't call "for ask for email feedback" dialog, so maybe you olso can add it? Becouse in my situation i am link in deadlock with my case.

**Comment by SuddenH4X** [comment]
Hi @Monabr,

please execuse my late reply (I was on holiday).
I'm currently implementing the new [Google in-app review API](https://developer.android.com/guide/playcore/in-app-review), so you can display the in-app review directly instead of showing the library dialog. Would you still use the requested features or would you rather use the new in-app review?
