### ISSUE TITLE
Add method to check if the rating popup is going to appear

### ISSUE THREAD

**Issue by rosenpin** [SuddenH4X/awesome-app-rating#41]
Sometimes at the app startup, you show a user some random pop ups, like permission request, a warning, a deal etc.

It would be good if this library will provide a function that returns a boolean value letting us know if it's going to pop up, in which case we can choose not to show all other pop ups (many pop ups will confuse the user and will most likely cause in ignoring the app rating pop up)

I would like to suggest 2 approaches:

1. `showIfMeetsConditions` will return a boolean value, true for showing, false for not showing (doesn't meet conditions)
2. ``` kotlin
        AppRating.Builder(activity)
            .setDebug(true)
            .setMinimumLaunchTimes(5)
            .setMinimumDays(2)
            .setMinimumLaunchTimesToShowAgain(8)
            .setMinimumDaysToShowAgain(4)
           .setOnShouldShow({ shouldShow->
                   // handle a situation where the dialog is shown/not shown
            })
            .showIfMeetsConditions()
```

**Comment by SuddenH4X** [comment]
Hi @rosenpin,

thanks for opening this issue. Currently you could use `.setCustomCondition(customCondition: () -> Boolean)` to get a similar behaviour. Set the custom condition to false, if you are displaying another dialog, otherwise true. So the rating dialog would not show up with other dialogs. Is this fixing your problem?

**Comment by rosenpin** [comment]
This is a working work around, but it's definitely not the most elegant way of doing this

I believe it would be useful to add a method like the one I described, it could make using this library work better with most flows, as opposed to forcing users to use the library flow

Let me know what you think :)

**Comment by SuddenH4X** [comment]
I don't think that `.setCustomCondition(customCondition: () -> Boolean)` is really a workaround. But with that method you only have the option to delay the rating dialog to the next time instead of the other dialogs. Additionally your first suggestion is really simple to implement and makes sense, so it will be in the next release 😉

**Comment by rosenpin** [comment]
Awesome!

Glad to hear :)

I meant it's a workaround for my specific need, not for all cases

**Comment by SuddenH4X** [comment]
Function added with #45.
