### ISSUE TITLE
Rename setMinimumLaunchTimes and setMinimumDays to something that describes its behaviour 

### ISSUE THREAD

**Issue by VinodRanganath** [SuddenH4X/awesome-app-rating#54]
setMinimumLaunchTimes is incremented on every attempt to show the dialog. But the name 'setMinimumLaunchTimes' seems to imply app launches. Please consider renaming this method as it might lead to confusions about its implementation.

**Comment by VinodRanganath** [comment]
setMinimumDays should also be renamed. It is described to take minimum days since app is installed. But actually it should be described as minimum days since dialog is shown previously.

**Comment by SuddenH4X** [comment]
HI @VinodRanganath, thanks for opening this issue. I will optimize the description of the methods. But I think renaming the methods to something like `setMinimumDaysSinceFirstBuilderCall` would be more confusing than the current naming.

In fact most of the developers are using the methods as descriped in the readme and therefore the launch times are indeed incremented on every app launch (`onCreate()` with `savedInstanceState == null`).  Also the minimum days are counted since the first builder call and not since the dialog was shown. So the minimum days should reflect the minimum days since the app was installed (first app start).

**Comment by VinodRanganath** [comment]
As per the implementation, it looks like the remindTimestamp is being set only on first call of showIfMeetsConditions. Can you verify? Sorry if I'm missing something.

**Comment by SuddenH4X** [comment]
You're right, the `remindTimestamp` is set on the first call of `showIfMeetsConditions()` only. What I meant to say is that most of the developers call the method `showIfMeetsConditions()` in their main activities `onCreate()`. And therefore the `remindTimestamp` will be set with the first app start (= days since first app start) and the `launchTimes` will be increased with every app start (= launch times).
