### ISSUE TITLE
No methods to set rating dialog mail Title's and cancel button's text

### ISSUE THREAD

**Issue by Glutius** [SuddenH4X/awesome-app-rating#66]
Hello, currently playing with your library and so far, so good. Only thing missing, that was probably forgotten but easy to fix, is the two methods here to change the title and cancel button text in the rating dialog with mail feedback, so that I don't have to create my own.
![image](https://user-images.githubusercontent.com/12672076/146740061-adfe6ae3-720c-4323-ba7b-1f13888db3ad.png)

**Comment by SuddenH4X** [comment]
Hi @Glutius, the cancel button text can be changed with the method `setNoFeedbackButtonTextId(noFeedbackButtonTextId: Int)` and the title with `setFeedbackTitleTextId(feedbackTitleTextId: Int)`. You can find them within the code below the comment `// rating dialog feedback` because this methods can be used with both feedback options (mail and custom feedback).

**Comment by Glutius** [comment]
My bad then, closing the issue. ;)
